### ISSUE TITLE
Getting "error: Cannot find module 'apidoc-core/lib/utils/trim'" error

### ISSUE THREAD

**Issue by hussaintamboli** [koko-ng/apidoc-contentType-plugin#1]
I had tried `apidoc` a year ago. I didn't like the fact that it didn't have json body support. I had even created https://github.com/hussaintamboli/apidoc-samples

Recently I thought I should check whether it's added and found your repo. I am getting below error when I try the command you have mentioned for content type,

    $ apidoc -i myapp/ -o doc -t ../apidoc-contentType-plugin/template/ --parse-parsers apicontenttype=../apidoc-contentType-plugin/api_content_type.js
    error: Cannot find module 'apidoc-core/lib/utils/trim'

**Comment by koko-ng** [comment]
Hi,
Nice to see someone interested in this project :).
Have you run `npm install` in ../apidoc-contentType-plugin ? Does node_modules in apidoc-contentType-plugin contains a directory called apidoc-core?

**Comment by hussaintamboli** [comment]
Yes. I forgot to do `npm install`. My bad :)  Thanks.

It's very important what you have provided and it should be part of `apidoc` I think.

**Comment by koko-ng** [comment]
Nice to hear your feedback. If you think it's worth including in apidoc you can support my pull request https://github.com/apidoc/apidoc/pull/601.

**Comment by hussaintamboli** [comment]
Sure. Done.
